env:
  commonjs: false
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: false
  ecmaVersion: 2018
rules: {
  "comma-dangle": [
    2,
    "always-multiline"
  ],
  "indent": [
    2,
    4
  ],
}
